apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: edefazs1a-java-quarkus 
  janus-idp.io/tekton: edefazs1a-java-quarkus
  backstage.io/kubernetes-id: edefazs1a-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: edefazs1a-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml